In [1]:
import math

print(math.pi)

3.141592653589793


In [2]:
from modules.data_preprocessing import clean_data

clean_data()

Cleaned data.


### Module Exercise

In [4]:
import json

with open('./modules/data.json','r') as file:
    data = json.load(file)

print(data)


{'name': 'Jared', 'age': 23}


In [1]:
import numpy as np
import pandas as pd

array = np.array([1, 2, 3, 4, 5])

array

array([1, 2, 3, 4, 5])

In [2]:
data = {'ID': [1, 2, 3, 4],
        'Address': ['a', 'b', 'c', 'd'],
        'Sales': [123, 456, 789, 100]}

df = pd.DataFrame(data)
print(df)

   ID Address  Sales
0   1       a    123
1   2       b    456
2   3       c    789
3   4       d    100


In [8]:
average = df['Sales'].mean()

print(average)

367.0


In [9]:
def add(a,b):
    """
    Add two numbers together.

    Parameters:
    a (int): First Number
    b (int): Second Number

    Returns:
    int: Sum of the two numbers
    """
    return a + b

help(add)

Help on function add in module __main__:

add(a, b)
    Add two numbers together.

    Parameters:
    a (int): First Number
    b (int): Second Number

    Returns:
    int: Sum of the two numbers



In [13]:
def multiply(a, b):
    """
    Multiply two numbers together.

    Parameters:
    a (int): First Number
    b (int): Second Number

    Returns:
    int: Product of the two numbers
    """
    return a * b


print(multiply(3, 7))
help(multiply)

21
Help on function multiply in module __main__:

multiply(a, b)
    Multiply two numbers together.

    Parameters:
    a (int): First Number
    b (int): Second Number

    Returns:
    int: Product of the two numbers



In [21]:
import numpy as np

# 1D ndarray
array1 = np.array([1, 2, 3])
print(array1.shape)

# 2D ndarray
array2 = np.array([[1, 2, 3], [1, 2, 3]])
print(array2.shape)

# Type coercion
array3 = np.array([3.14, 2, 3])
print(array3) # converts everything to float64
print(type(array3[1]))

# Explicit Type Coercion
array4 = np.array([3.14, 2, 3], dtype=np.int64) # dtype = data type for array
print(array4)

(3,)
(2, 3)
[3.14 2.   3.  ]
<class 'numpy.float64'>
[3 2 3]


In [39]:
import numpy as np

a = np.array([10,20,30,40])
b = np.arange(4) # create array from 0 to 3

d = a + b
print(d)
d = a - b
print(d)
d = a * b
print(d)
d = np.array(b * a / a, dtype=np.int64)
print(d)

[10 21 32 43]
[10 19 28 37]
[  0  20  60 120]
[0 1 2 3]
